services:
  - type: web
    name: hospital-angel-maria-gaton-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: PORT
        value: 10000
      - key: ALLOWED_ORIGIN
        value: https://joelcolon2012-lang.github.io
